### ISSUE TITLE
Domain question

### ISSUE THREAD

**Issue by 89z** [ashvin-bhuttoo/RarbgAdvancedSearch#10]
Why are you not using `rarbg.to`?

https://github.com/ashvin-bhuttoo/RarbgAdvancedSearch/blob/189511db5aa843587a0213c56c657799757b76a9/RarbgAdvancedSearch/Main.cs#L90

**Comment by ashvin-bhuttoo** [comment]
rarbg.to is always redirected to rarbgenter.org when doing a search

**Comment by 89z** [comment]
No, its not:

https://rarbg.to/torrents.php?search=three+colors

**Comment by ashvin-bhuttoo** [comment]
For me its redirecting to 
https://rarbgenter.org/torrents.php?search=three+colors

I guess there's some kind of ip geolocation based redirection.
