### ISSUE TITLE
Imdb rating broken?

### ISSUE THREAD

**Issue by fredguile** [ashvin-bhuttoo/RarbgAdvancedSearch#12]
Pretty nifty tool! However the IMDB rating doesn't seem to work? All search results show "0" on my side...

**Comment by ashvin-bhuttoo** [comment]
Hi, the IMDB ratings on the tool's table only show up with a value if the listing on rarbg has the rating defined as description. 
i.e. "Comedy, Family, Drama, Crime IMDB: 6.2/10"
A lot of rarbg entries do not have this description which results in zero rating, then you will have to rely on the imdb rating seen when your mouse hovers on a listing in the tool which is the actual rating fetched dynamically from imdb.com
