### ISSUE TITLE
IMDB Rating is not working

### ISSUE THREAD

**Issue by gokhanko** [ashvin-bhuttoo/RarbgAdvancedSearch#13]
IMDB Rating is not working, please update.

Can you add option to export magnets as txt?

**Comment by ashvin-bhuttoo** [comment]
Hi, the IMDB ratings on the tool's table only show up with a value if the listing on rarbg has the rating defined as description. 
i.e. "Comedy, Family, Drama, Crime IMDB: 6.2/10"
A lot of rarbg entries do not have this description which results in zero rating, then you will have to rely on the imdb rating seen when your mouse hovers on a listing in the tool which is the actual rating fetched dynamically from imdb.com

As for the export of magnet as text, when you right click on an entry, you have the option to "Copy Magnet link" which is a text version of the magnet that is copied and you can paste anywhere.
