### ISSUE TITLE
Can't be installed

### ISSUE THREAD

**Issue by hansolocambo** [ashvin-bhuttoo/RarbgAdvancedSearch#15]
Setup.exe                             ->   "An error occured attempting to install [...]"
RarbgAdvancedSearch.msi   ->   "There is a problem with the Windows Installer Package [...]"

:/

**Comment by ashvin-bhuttoo** [comment]
Can you please download the NSIS version of the installer and try to install with that:

https://github.com/ashvin-bhuttoo/RarbgAdvancedSearch/releases/tag/1.1.0

![image](https://user-images.githubusercontent.com/17810392/122000988-b0e2ca80-cdc0-11eb-8f3e-f8a22646aa38.png)

**Comment by ashvin-bhuttoo** [comment]
duplicate of #11
