### ISSUE TITLE
Feature Request Min Number of IMDB Votes

### ISSUE THREAD

**Issue by TehBotolSosro** [ashvin-bhuttoo/RarbgAdvancedSearch#8]
it would be great if the program could filter by Minimum XXX number of imdb votes 
and even sort them by votes, since the number of rating is pointless if it's only 100 or less votes

also if it's possible sort by the most comment'ed

**Comment by ashvin-bhuttoo** [comment]
hey there, i am aware of this limitation and actually wanted to implemented that one but this feature would significantly increase network overhead on imdb.com as this data is not readily available on rarbg through the listing page, for now i can put this information on the imdb preview panel when you hover on the listing. I will think of a way to decrease the overhead on imdb maybe i can host a mirror or something.

**Comment by TehBotolSosro** [comment]
yeah i think with how the current program work, i don't think it's possible to include the imdb rating since the info is available only on the individual torrent page but not on the index

it's different if the program is a database based, maybe in the future you can create another program that have all the individual torrent info on a database but i think it would be big database :D 

thanks for clarification though 👍
